version: '3.7'

services:
  # FastAPI application
  app:
    image: sovathcc/fastapi-memolog:1.0.0-uat
    container_name: memo_app
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file:
      - .env
    command: fastapi run main.py --host 0.0.0.0
    networks:
      - myapp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.memo-api.rule=Host(`postiz.komror.com`)"
      - "traefik.http.routers.memo-api.entrypoints=websecure"
      - "traefik.http.routers.memo-api.tls=true"
      - "traefik.http.routers.memo-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.memo-api.loadbalancer.server.port=8001"

networks:
  myapp:
    external: true
